In [1]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
brcd = datasets.load_breast_cancer()
X, y = brcd.data, brcd.target

In [7]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
n_samples, n_features = X.shape

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=1818)
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [27]:
y_train = y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)

In [28]:
y_train

tensor([[1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [29]:
class Model(nn.Module):
    def __init__(self,n_input_features):
        super(Model,self).__init__()
        self.linear=nn.Linear(n_input_features,1)
    def forward(self,x):
        y_pred=torch.sigmoid(self.linear(x))
        return y_pred    

In [30]:
model=Model(n_features)

In [37]:
num_epochs=10000
learning_rate=0.001
criterion=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [39]:
for epoch in range(num_epochs):
    y_pred=model(X_train)
    loss=criterion(y_pred,y_train)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if (epoch+1) % 100 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')
    

epoch: 100, loss = 0.1042
epoch: 200, loss = 0.1039
epoch: 300, loss = 0.1035
epoch: 400, loss = 0.1032
epoch: 500, loss = 0.1029
epoch: 600, loss = 0.1026
epoch: 700, loss = 0.1023
epoch: 800, loss = 0.1020
epoch: 900, loss = 0.1017
epoch: 1000, loss = 0.1014
epoch: 1100, loss = 0.1011
epoch: 1200, loss = 0.1008
epoch: 1300, loss = 0.1005
epoch: 1400, loss = 0.1003
epoch: 1500, loss = 0.1000
epoch: 1600, loss = 0.0997
epoch: 1700, loss = 0.0995
epoch: 1800, loss = 0.0992
epoch: 1900, loss = 0.0989
epoch: 2000, loss = 0.0987
epoch: 2100, loss = 0.0984
epoch: 2200, loss = 0.0982
epoch: 2300, loss = 0.0979
epoch: 2400, loss = 0.0977
epoch: 2500, loss = 0.0975
epoch: 2600, loss = 0.0972
epoch: 2700, loss = 0.0970
epoch: 2800, loss = 0.0968
epoch: 2900, loss = 0.0965
epoch: 3000, loss = 0.0963
epoch: 3100, loss = 0.0961
epoch: 3200, loss = 0.0959
epoch: 3300, loss = 0.0957
epoch: 3400, loss = 0.0955
epoch: 3500, loss = 0.0953
epoch: 3600, loss = 0.0950
epoch: 3700, loss = 0.0948
epoch: 380

In [40]:
with torch.no_grad():
    y_predicted = model(X_test)
    y_predicted_cls = y_predicted.round()
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

accuracy: 0.9884


In [41]:
X_test[0]

tensor([-0.9335,  2.9597, -0.9962, -0.8891, -1.2788, -1.3208, -1.0698, -1.1756,
         0.0141, -0.5638, -0.7109,  0.7862, -0.7662, -0.7023, -1.0457, -0.9826,
        -0.7045, -1.2979, -0.1490, -0.4239, -0.9072,  2.3021, -0.9623, -0.8306,
        -1.4292, -1.1888, -1.2535, -1.3790, -0.1196, -0.6219])